### ISSUE TITLE
Crashing when Trying To Add a tag

### ISSUE THREAD

**Issue by techie2000** [mikenye/docker-picard#25]
I'm getting consistent/repeatable crashing when trying to add a new tag (editing existing tags is fine) which results in a need to restart the container.

The container log records :
```
Traceback (most recent call last):
File "/usr/lib/picard/picard/ui/edittagdialog.py", line 132, in tag_selected
self.add_or_edit_value()
File "/usr/lib/picard/picard/ui/edittagdialog.py", line 151, in add_or_edit_value
self.edit_value()
File "/usr/lib/picard/picard/ui/edittagdialog.py", line 136, in edit_value
if item and not self.value_list.isPersistentEditorOpen(item):
AttributeError: 'QListWidget' object has no attribute 'isPersistentEditorOpen'
Aborted
[services.d] stopping services
[services.d] stopping app...
[services.d] stopping x11vnc...
caught signal: 15
18/10/2020 17:34:35 deleted 75 tile_row polling images.
18/10/2020 17:34:35 Restored X server key autorepeat to: 1
[services.d] stopping openbox...
[services.d] stopping statusmonitor...
[services.d] stopping logmonitor...
[services.d] stopping xvfb...
[5191:5191:1018/173435.984016:ERROR:x11_error_handler.cc(64)] X IO error received (X server probably went away)

[5217:5217:1018/173435.986870:ERROR:x11_util.cc(112)] X IO error received (X server probably went away)

[5191:5202:1018/173436.027282:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
[services.d] stopping nginx...
[services.d] stopping certsmonitor...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
Trace/breakpoint trap
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted

Trace/breakpoint trap
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: firefox: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: chromium: not found
[7995:7995:0100/000000.106968:ERROR:zygote_linux.cc(654)] write: Broken pipe (32)

[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by mikenye** [comment]
Hi @techie2000, can you give me a process I can follow to reproduce the error?

Looking at the error message you've posted, it looks like that error is being thrown by Picard itself (not the container):

```
Traceback (most recent call last):
File "/usr/lib/picard/picard/ui/edittagdialog.py", line 132, in tag_selected
self.add_or_edit_value()
File "/usr/lib/picard/picard/ui/edittagdialog.py", line 151, in add_or_edit_value
self.edit_value()
File "/usr/lib/picard/picard/ui/edittagdialog.py", line 136, in edit_value
if item and not self.value_list.isPersistentEditorOpen(item):
AttributeError: 'QListWidget' object has no attribute 'isPersistentEditorOpen'
```

I'll have a look on the Picard github issues section today to see if anyone else is reporting a problem.

Does it only occur with the latest version of Picard? Have you tried any other versions?

Thanks.

**Comment by mikenye** [comment]
Hi @techie2000, I spent some time refactoring the dockerfile - are you able to try out `mikenye/picard:issue_25` to see if that's any better?

**Comment by techie2000** [comment]
Hi @mikenye 
I'll fire up an example and record the steps shortly (work permitting!)

I have tried the :issue25 flavour but can't get that to stay up. Docker log output is :


```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing...
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing...
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting certsmonitor...
[services.d] starting nginx...
[services.d] starting xvfb...
[nginx] starting...
[certsmonitor] disabling service: secure connection not enabled.
[xvfb] starting...
[services.d] starting logmonitor...
[services.d] starting statusmonitor...
[logmonitor] no file to monitor: disabling service...
[services.d] starting openbox...
[statusmonitor] no file to monitor: disabling service...
[openbox] starting...
[services.d] starting x11vnc...
[services.d] starting app...
[x11vnc] starting...
[app] starting MusicBrainz Picard...
+ HOME=/config
+ export HOME
+ rm -rf /config/xdg/config/chromium/Singleton*
[services.d] done.
+ /usr/bin/picard
19/10/2020 11:12:56 /startapp.sh: 12: /startapp.sh: passing arg to libvncserver: -rfbport
/usr/bin/picard: not found
19/10/2020 11:12:56 passing arg to libvncserver: 5900
19/10/2020 11:12:56 passing arg to libvncserver: -rfbportv6
19/10/2020 11:12:56 passing arg to libvncserver: -1
19/10/2020 11:12:56 passing arg to libvncserver: -httpportv6
19/10/2020 11:12:56 passing arg to libvncserver: -1
19/10/2020 11:12:56 passing arg to libvncserver: -desktop
19/10/2020 11:12:56 passing arg to libvncserver: MusicBrainz Picard
19/10/2020 11:12:56 x11vnc version: 0.9.14 lastmod: 2015-11-14 pid: 902

19/10/2020 11:12:56 Using X display :0
19/10/2020 11:12:56 rootwin: 0x298 reswin: 0x400001 dpy: 0x1bcbf550
19/10/2020 11:12:56
19/10/2020 11:12:56 ------------------ USEFUL INFORMATION ------------------
19/10/2020 11:12:56 X DAMAGE available on display, using it for polling hints.
19/10/2020 11:12:56 To disable this behavior use: '-noxdamage'
19/10/2020 11:12:56
19/10/2020 11:12:56 Most compositing window managers like 'compiz' or 'beryl'
19/10/2020 11:12:56 cause X DAMAGE to fail, and so you may not see any screen
19/10/2020 11:12:56 updates via VNC. Either disable 'compiz' (recommended) or
19/10/2020 11:12:56 supply the x11vnc '-noxdamage' command line option.
19/10/2020 11:12:56 X COMPOSITE available on display, using it for window polling.
19/10/2020 11:12:56 To disable this behavior use: '-noxcomposite'
19/10/2020 11:12:56
19/10/2020 11:12:56 Wireframing: -wireframe mode is in effect for window moves.
19/10/2020 11:12:56 If this yields undesired behavior (poor response, painting
19/10/2020 11:12:56 errors, etc) it may be disabled:
19/10/2020 11:12:56 - use '-nowf' to disable wireframing completely.
19/10/2020 11:12:56 - use '-nowcr' to disable the Copy Rectangle after the
19/10/2020 11:12:56 moved window is released in the new position.
19/10/2020 11:12:56 Also see the -help entry for tuning parameters.
19/10/2020 11:12:56 You can press 3 Alt_L's (Left "Alt" key) in a row to
19/10/2020 11:12:56 repaint the screen, also see the -fixscreen option for
19/10/2020 11:12:56 periodic repaints.
19/10/2020 11:12:56 GrabServer control via XTEST.
19/10/2020 11:12:56
19/10/2020 11:12:56 Scroll Detection: -scrollcopyrect mode is in effect to
19/10/2020 11:12:56 use RECORD extension to try to detect scrolling windows
19/10/2020 11:12:56 (induced by either user keystroke or mouse input).

19/10/2020 11:12:56 If this yields undesired behavior (poor response, painting
19/10/2020 11:12:56 errors, etc) it may be disabled via: '-noscr'
19/10/2020 11:12:56 Also see the -help entry for tuning parameters.
19/10/2020 11:12:56 You can press 3 Alt_L's (Left "Alt" key) in a row to
19/10/2020 11:12:56 repaint the screen, also see the -fixscreen option for
19/10/2020 11:12:56 periodic repaints.
19/10/2020 11:12:56
19/10/2020 11:12:56 XKEYBOARD: number of keysyms per keycode 7 is greater
19/10/2020 11:12:56 than 4 and 51 keysyms are mapped above 4.
19/10/2020 11:12:56 Automatically switching to -xkb mode.
19/10/2020 11:12:56 If this makes the key mapping worse you can
19/10/2020 11:12:56 disable it with the "-noxkb" option.
19/10/2020 11:12:56 Also, remember "-remap DEAD" for accenting characters.
19/10/2020 11:12:56
19/10/2020 11:12:56 X FBPM extension not supported.
19/10/2020 11:12:56 X display is not capable of DPMS.
19/10/2020 11:12:56 --------------------------------------------------------
19/10/2020 11:12:56
19/10/2020 11:12:56 Default visual ID: 0x21
19/10/2020 11:12:56 Read initial data from X display into framebuffer.
19/10/2020 11:12:56 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/9600
19/10/2020 11:12:56
19/10/2020 11:12:56 X display :0 is 32bpp depth=24 true color
19/10/2020 11:12:56
19/10/2020 11:12:56 Listening for VNC connections on TCP port 5900
19/10/2020 11:12:56
19/10/2020 11:12:56 Xinerama is present and active (e.g. multi-head).
19/10/2020 11:12:56 Xinerama: number of sub-screens: 1
19/10/2020 11:12:56 Xinerama: no blackouts needed (only one sub-screen)
19/10/2020 11:12:56
19/10/2020 11:12:56 fb read rate: 2092 MB/sec
19/10/2020 11:12:56 fast read: reset -wait ms to: 10
19/10/2020 11:12:56 fast read: reset -defer ms to: 10
19/10/2020 11:12:56 The X server says there are 10 mouse buttons.

19/10/2020 11:12:56 screen setup finished.
19/10/2020 11:12:56

The VNC desktop is: baf2a722eac0:0

0

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval. It should work with any VNC viewer. Try it by running:

x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

[services.d] stopping services
[services.d] starting x11vnc...
[services.d] starting app...
[x11vnc] starting...
[app] starting MusicBrainz Picard...
+ HOME=/config
+ export HOME
+ rm -rf /config/xdg/config/chromium/Singleton*
[services.d] done.
+ /usr/bin/picard
19/10/2020 11:12:56 /startapp.sh: 12: /startapp.sh: passing arg to libvncserver: -rfbport
/usr/bin/picard: not found
19/10/2020 11:12:56 passing arg to libvncserver: 5900
19/10/2020 11:12:56 passing arg to libvncserver: -rfbportv6
19/10/2020 11:12:56 passing arg to libvncserver: -1
19/10/2020 11:12:56 passing arg to libvncserver: -httpportv6
19/10/2020 11:12:56 passing arg to libvncserver: -1
19/10/2020 11:12:56 passing arg to libvncserver: -desktop
19/10/2020 11:12:56 passing arg to libvncserver: MusicBrainz Picard
19/10/2020 11:12:56 x11vnc version: 0.9.14 lastmod: 2015-11-14 pid: 902

19/10/2020 11:12:56 Using X display :0
19/10/2020 11:12:56 rootwin: 0x298 reswin: 0x400001 dpy: 0x1bcbf550
19/10/2020 11:12:56
19/10/2020 11:12:56 ------------------ USEFUL INFORMATION ------------------
19/10/2020 11:12:56 X DAMAGE available on display, using it for polling hints.
19/10/2020 11:12:56 To disable this behavior use: '-noxdamage'
19/10/2020 11:12:56
19/10/2020 11:12:56 Most compositing window managers like 'compiz' or 'beryl'
19/10/2020 11:12:56 cause X DAMAGE to fail, and so you may not see any screen
19/10/2020 11:12:56 updates via VNC. Either disable 'compiz' (recommended) or
19/10/2020 11:12:56 supply the x11vnc '-noxdamage' command line option.
19/10/2020 11:12:56 X COMPOSITE available on display, using it for window polling.
19/10/2020 11:12:56 To disable this behavior use: '-noxcomposite'
19/10/2020 11:12:56
19/10/2020 11:12:56 Wireframing: -wireframe mode is in effect for window moves.
19/10/2020 11:12:56 If this yields undesired behavior (poor response, painting
19/10/2020 11:12:56 errors, etc) it may be disabled:
19/10/2020 11:12:56 - use '-nowf' to disable wireframing completely.
19/10/2020 11:12:56 - use '-nowcr' to disable the Copy Rectangle after the
19/10/2020 11:12:56 moved window is released in the new position.
19/10/2020 11:12:56 Also see the -help entry for tuning parameters.
19/10/2020 11:12:56 You can press 3 Alt_L's (Left "Alt" key) in a row to
19/10/2020 11:12:56 repaint the screen, also see the -fixscreen option for
19/10/2020 11:12:56 periodic repaints.
19/10/2020 11:12:56 GrabServer control via XTEST.
19/10/2020 11:12:56
19/10/2020 11:12:56 Scroll Detection: -scrollcopyrect mode is in effect to
19/10/2020 11:12:56 use RECORD extension to try to detect scrolling windows
19/10/2020 11:12:56 (induced by either user keystroke or mouse input).

19/10/2020 11:12:56 If this yields undesired behavior (poor response, painting
19/10/2020 11:12:56 errors, etc) it may be disabled via: '-noscr'
19/10/2020 11:12:56 Also see the -help entry for tuning parameters.
19/10/2020 11:12:56 You can press 3 Alt_L's (Left "Alt" key) in a row to
19/10/2020 11:12:56 repaint the screen, also see the -fixscreen option for
19/10/2020 11:12:56 periodic repaints.
19/10/2020 11:12:56
19/10/2020 11:12:56 XKEYBOARD: number of keysyms per keycode 7 is greater
19/10/2020 11:12:56 than 4 and 51 keysyms are mapped above 4.
19/10/2020 11:12:56 Automatically switching to -xkb mode.
19/10/2020 11:12:56 If this makes the key mapping worse you can
19/10/2020 11:12:56 disable it with the "-noxkb" option.
19/10/2020 11:12:56 Also, remember "-remap DEAD" for accenting characters.
19/10/2020 11:12:56
19/10/2020 11:12:56 X FBPM extension not supported.
19/10/2020 11:12:56 X display is not capable of DPMS.
19/10/2020 11:12:56 --------------------------------------------------------
19/10/2020 11:12:56
19/10/2020 11:12:56 Default visual ID: 0x21
19/10/2020 11:12:56 Read initial data from X display into framebuffer.
19/10/2020 11:12:56 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/9600
19/10/2020 11:12:56
19/10/2020 11:12:56 X display :0 is 32bpp depth=24 true color
19/10/2020 11:12:56
19/10/2020 11:12:56 Listening for VNC connections on TCP port 5900
19/10/2020 11:12:56
19/10/2020 11:12:56 Xinerama is present and active (e.g. multi-head).
19/10/2020 11:12:56 Xinerama: number of sub-screens: 1
19/10/2020 11:12:56 Xinerama: no blackouts needed (only one sub-screen)
19/10/2020 11:12:56
19/10/2020 11:12:56 fb read rate: 2092 MB/sec
19/10/2020 11:12:56 fast read: reset -wait ms to: 10
19/10/2020 11:12:56 fast read: reset -defer ms to: 10
19/10/2020 11:12:56 The X server says there are 10 mouse buttons.

19/10/2020 11:12:56 screen setup finished.
19/10/2020 11:12:56

The VNC desktop is: baf2a722eac0:0

0

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval. It should work with any VNC viewer. Try it by running:

x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

[services.d] stopping services
[services.d] stopping app...
[services.d] stopping x11vnc...
caught signal: 15
19/10/2020 11:12:56 deleted 75 tile_row polling images.
[services.d] stopping openbox...
[services.d] stopping statusmonitor...
[services.d] stopping logmonitor...
[services.d] stopping xvfb...
[services.d] stopping nginx...
[services.d] stopping certsmonitor...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by mikenye** [comment]
I've fixed `mikenye/picard:issue_25` if you'd like to give it another go. Cheers.

**Comment by techie2000** [comment]
Hi @mikenye 

> can you give me a process I can follow to reproduce the error?

1. Drag an(y) .mp3 into middle-top pane.
2. Observe the current tags in the lower third pane.
3. Right-click in the lower third pane and select "add new tag".
3. New pop-up form is displayed.
4. Use the drop-down/combo-box to pick a tag.
5. Observe crash when making any selection.

> Does it only occur with the latest version of Picard? Have you tried any other versions?

I've been seeing it for a few weeks through a couple of docker updates (as a result of Picard backend update being applied). I have not gone back to any prior versions to investigate.

> I've fixed mikenye/picard:issue_25 if you'd like to give it another go. Cheers.

Thx. I'll give it another try

**Comment by mikenye** [comment]
Thanks. I’ll check it out.

**Comment by techie2000** [comment]
> I've fixed mikenye/picard:issue_25 if you'd like to give it another go. Cheers.

Still can't get this to stay up : 

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing...
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing...
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting certsmonitor...
[services.d] starting nginx...
[services.d] starting xvfb...
[nginx] starting...
[certsmonitor] disabling service: secure connection not enabled.
[xvfb] starting...
[services.d] starting logmonitor...
[services.d] starting statusmonitor...
[logmonitor] no file to monitor: disabling service...
[statusmonitor] no file to monitor: disabling service...
[services.d] starting openbox...
[openbox] starting...
[services.d] starting x11vnc...
[services.d] starting app...
[app] starting MusicBrainz Picard...
[x11vnc] starting...
[services.d] done.
+ HOME=/config
+ export HOME
+ rm -rf /config/xdg/config/chromium/Singleton*
+ /usr/local/bin/picard
19/10/2020 13:41:07 passing arg to libvncserver: -rfbport
19/10/2020 13:41:07 passing arg to libvncserver: 5900
19/10/2020 13:41:07 passing arg to libvncserver: -rfbportv6
19/10/2020 13:41:07 passing arg to libvncserver: -1
19/10/2020 13:41:07 passing arg to libvncserver: -httpportv6
19/10/2020 13:41:07 passing arg to libvncserver: -1
19/10/2020 13:41:07 passing arg to libvncserver: -desktop
19/10/2020 13:41:07 passing arg to libvncserver: MusicBrainz Picard
19/10/2020 13:41:07 x11vnc version: 0.9.14 lastmod: 2015-11-14 pid: 901

19/10/2020 13:41:07 Using X display :0
19/10/2020 13:41:07 rootwin: 0x298 reswin: 0x400001 dpy: 0x743c550
19/10/2020 13:41:07
19/10/2020 13:41:07 ------------------ USEFUL INFORMATION ------------------
19/10/2020 13:41:07 X DAMAGE available on display, using it for polling hints.
19/10/2020 13:41:07 To disable this behavior use: '-noxdamage'
19/10/2020 13:41:07
19/10/2020 13:41:07 Most compositing window managers like 'compiz' or 'beryl'
19/10/2020 13:41:07 cause X DAMAGE to fail, and so you may not see any screen
19/10/2020 13:41:07 updates via VNC. Either disable 'compiz' (recommended) or
19/10/2020 13:41:07 supply the x11vnc '-noxdamage' command line option.
19/10/2020 13:41:07 X COMPOSITE available on display, using it for window polling.
19/10/2020 13:41:07 To disable this behavior use: '-noxcomposite'
19/10/2020 13:41:07
19/10/2020 13:41:07 Wireframing: -wireframe mode is in effect for window moves.
19/10/2020 13:41:07 If this yields undesired behavior (poor response, painting
19/10/2020 13:41:07 errors, etc) it may be disabled:
19/10/2020 13:41:07 - use '-nowf' to disable wireframing completely.
19/10/2020 13:41:07 - use '-nowcr' to disable the Copy Rectangle after the
19/10/2020 13:41:07 moved window is released in the new position.
19/10/2020 13:41:07 Also see the -help entry for tuning parameters.
19/10/2020 13:41:07 You can press 3 Alt_L's (Left "Alt" key) in a row to
19/10/2020 13:41:07 repaint the screen, also see the -fixscreen option for
19/10/2020 13:41:07 periodic repaints.
19/10/2020 13:41:07 GrabServer control via XTEST.
19/10/2020 13:41:07
19/10/2020 13:41:07 Scroll Detection: -scrollcopyrect mode is in effect to
19/10/2020 13:41:07 use RECORD extension to try to detect scrolling windows
19/10/2020 13:41:07 (induced by either user keystroke or mouse input).

19/10/2020 13:41:07 If this yields undesired behavior (poor response, painting
19/10/2020 13:41:07 errors, etc) it may be disabled via: '-noscr'
19/10/2020 13:41:07 Also see the -help entry for tuning parameters.
19/10/2020 13:41:07 You can press 3 Alt_L's (Left "Alt" key) in a row to
19/10/2020 13:41:07 repaint the screen, also see the -fixscreen option for
19/10/2020 13:41:07 periodic repaints.
19/10/2020 13:41:07
19/10/2020 13:41:07 XKEYBOARD: number of keysyms per keycode 7 is greater
19/10/2020 13:41:07 than 4 and 51 keysyms are mapped above 4.
19/10/2020 13:41:07 Automatically switching to -xkb mode.
19/10/2020 13:41:07 If this makes the key mapping worse you can
19/10/2020 13:41:07 disable it with the "-noxkb" option.
19/10/2020 13:41:07 Also, remember "-remap DEAD" for accenting characters.
19/10/2020 13:41:07
19/10/2020 13:41:07 X FBPM extension not supported.
19/10/2020 13:41:07 X display is not capable of DPMS.
19/10/2020 13:41:07 --------------------------------------------------------
19/10/2020 13:41:07
19/10/2020 13:41:07 Default visual ID: 0x21
19/10/2020 13:41:07 Read initial data from X display into framebuffer.
19/10/2020 13:41:07 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/9600
19/10/2020 13:41:07
19/10/2020 13:41:07 X display :0 is 32bpp depth=24 true color
19/10/2020 13:41:07
19/10/2020 13:41:07 Listening for VNC connections on TCP port 5900
19/10/2020 13:41:07
19/10/2020 13:41:07 Xinerama is present and active (e.g. multi-head).
19/10/2020 13:41:07 Xinerama: number of sub-screens: 1
19/10/2020 13:41:07 Xinerama: no blackouts needed (only one sub-screen)
19/10/2020 13:41:07
19/10/2020 13:41:07 fb read rate: 2080 MB/sec
19/10/2020 13:41:07 fast read: reset -wait ms to: 10
19/10/2020 13:41:07 fast read: reset -defer ms to: 10
19/10/2020 13:41:07 The X server says there are 10 mouse buttons.

19/10/2020 13:41:07 screen setup finished.
19/10/2020 13:41:07

The VNC desktop is: a9694931e532:0

0

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval. It should work with any VNC viewer. Try it by running:

x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.


Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted
[services.d] stopping services
[services.d] stopping app...
[services.d] stopping x11vnc...
caught signal: 15
19/10/2020 13:41:07 deleted 75 tile_row polling images.
[services.d] stopping openbox...
[services.d] stopping statusmonitor...
[services.d] stopping logmonitor...
[services.d] stopping xvfb...
[services.d] stopping nginx...
[services.d] stopping certsmonitor...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by mikenye** [comment]
Hi @techie2000,

Just letting you know I can reproduce your issue and it appears to be a problem with the version of Qt installed in the existing container.

I'm working on fixing it.

Thanks for your patience.

**Comment by mikenye** [comment]
Can you please give `mikenye/picard:issue_25` another try? The issue is fixed for me in that image.

If you report success I'll roll the changes into master.

Thanks.

**Comment by techie2000** [comment]
@mikenye `mikenye/picard:issue_25` looks stable under my testing conditions :)

**Comment by mikenye** [comment]
Hi @techie2000,

Changes have been merged into the `master` branch and the `latest` image rebuilt. Thanks again.

**Comment by techie2000** [comment]
`:latest` installed and seen to work as expected (as per `:issue_25` release

Thank-you for fixing :)

**Comment by mikenye** [comment]
No worries!
